### ISSUE TITLE
The script may not work on other than KataGo

### ISSUE THREAD

**Issue by changcheng22023** [changcheng967/OGS-Active-Game-Rank-Updater#3]
The script may not work on other than KataGo

**Comment by DouletMedia** [comment]
yeah, because the human AI is on KataGo 1.15.3 only

**Comment by changcheng967** [comment]
Yes, @DouletMedia is right

**Comment by changcheng967** [comment]
Changelog
2 minutes ago: Changcheng967 changed email address.
2 minutes ago: DouletMedia merged pull request #1 from changcheng22023/main.
4 minutes ago: Changcheng967 removed unnecessary code and files.
5 minutes ago: Changcheng22023 updated LICENSE file.
9 minutes ago: Changcheng967 updated README.md with new instructions.
11 minutes ago: Changcheng967 fixed rating handling and updated configuration file.
13 minutes ago: Changcheng967 added files via upload.
44 minutes ago: Changcheng967 made the initial commit with project setup and basic files.
